# Generated by Django 4.2.16 on 2024-09-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_en', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_en', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_desc')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_en', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='service_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio')),
                ('url_link', models.URLField()),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service')),
                ('tags', models.ManyToManyField(to='service_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('phone_number', models.CharField(max_length=125)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service')),
            ],
        ),
    ]
