# Generated by Django 4.2.16 on 2024-09-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('title_en', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'CategoryService',
                'verbose_name_plural': 'CategoryServices',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicedescription',
            options={'verbose_name': 'ServiceDescription', 'verbose_name_plural': 'ServiceDescriptions'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='service',
            name='category_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.categoryservice'),
        ),
    ]
