# Generated by Django 4.2.16 on 2024-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('tick', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('price', models.IntegerField()),
                ('limit_date', models.CharField(max_length=125)),
                ('limit_user', models.CharField(max_length=125)),
                ('features', models.ManyToManyField(to='main_app.feature')),
            ],
        ),
    ]
