# Generated by Django 4.2.16 on 2024-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feature_priceplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='limit_date_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='limit_date_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='limit_date_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='limit_user_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='limit_user_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='limit_user_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='title_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='priceplan',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
