# Generated by Django 4.2.16 on 2024-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feature_title_en_feature_title_ru_feature_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': 'FAQCategory', 'verbose_name_plural': 'FAQCategorys'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'FeedBack', 'verbose_name_plural': 'FeedBacks'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='priceplan',
            options={'verbose_name': 'PricePlan', 'verbose_name_plural': 'PricePlans'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Subscribe', 'verbose_name_plural': 'Subscribes'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name': 'WhyUs'},
        ),
        migrations.AddField(
            model_name='whyus',
            name='image',
            field=models.ImageField(default=4.49599856128046e-05, upload_to='whyus'),
            preserve_default=False,
        ),
    ]
