# Generated by Django 4.2.16 on 2024-09-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_certificate_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
